### ISSUE TITLE
Reset on exit missing

### ISSUE THREAD

**Issue by iansutherland75** [caewok/fvtt-terrain-mapper#41]
The checkbox for reset on exit appears to be missing in the "Set Elevation" behavior.

![image](https://github.com/user-attachments/assets/d5a74ce9-b0ab-4681-9089-51e2edf747c0)

**Comment by caewok** [comment]
Yeah, not really missing so much as removed. Here is how I currently view this (with caveat that I could probably be convinced otherwise):

1. If you are going up when entering at one location and down when exiting at another location, that suggests a physical hill or plateau. The plateau and ramp options I added in v0.4.0 handle this better because they assume a physical object and manipulate token elevation accordingly.
2. If you are using stairs, you are not really expecting to go up stairs, then wander around in the upstairs, and then magically fall off the upper level. A reset on exit creates that magical "falling off the upper level" effect.  "Set Elevation" in v0.4.0 acts like stairs. You probably want to size such a region accordingly (probably 1 grid space or so). That way, tokens can easily leave the stairs region and move back to move back down.

**Comment by iansutherland75** [comment]
I guess it's just confusing from a user perspective.  I was trying to create a region where the token went to 10, and then 0 again when it left, and I couldn't figure out how to do that.  Plateau / Mesa etc doesn't really help me visualize.  

I appreciate your work and I'm not complaining, but maybe I'm suggesting an easier way to understand what you're getting at. 

Reset on leaving was simple.

**Comment by Hazuma81** [comment]
I agree with what the user above wrote. The reset on exit button is definitely more intuitive , also the token might want to exit from where it entered consequently if I have a hill the token might enter , see enemies and then immediately exit from where it entered.
With the current version , this example , it keeps the token at the elevation of the hill. 
In my humble opinion it would be better to reintroduce the reset on exit button , the game master decides whether to implement the flag or not when creating the region.
I personally went back to the previous version of the module to have such functionality

**Comment by iansutherland75** [comment]
> I agree with what the user above wrote. The reset on exit button is definitely more intuitive , also the token might want to exit from where it entered consequently if I have a hill the token might enter , see enemies and then immediately exit from where it entered. With the current version , this example , it keeps the token at the elevation of the hill. In my humble opinion it would be better to reintroduce the reset on exit button , the game master decides whether to implement the flag or not when creating the region. I personally went back to the previous version of the module to have such functionality

Good Call.  I've just done the same.

**Comment by caewok** [comment]
See v0.4.2
