### ISSUE TITLE
Inconsistent Graphic Overlay

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-terrain-mapper#59]
I really like what you did with the region graphic, showing a slotted color graphic to communicate it is a ramp. However, it is sometimes inconsistent in showing the direction of the stairs. 

These West and East ramps have what should be the graphic oriented properly. 

![image](https://github.com/user-attachments/assets/c4386543-ab82-4b41-b756-655e76b45a53)

However, this same region in a different polygon shows the graphic oriented incorrectly. 

![image](https://github.com/user-attachments/assets/1dc17939-f36c-4671-815a-a562146401c8)

Similar to the last bug with orientation, it appears these graphics change when another polygon is created elsewhere on the map. It's important to note this is just a graphical bug, and the ramps are behaving correctly. 

Cheers on a GREAT mod, brother. This is absolutely indispensable in my mod pack now that I've showed it to my players. Having actual verisimilitude on ramps for exact elevation and difficult terrain (in our games, all stairs are difficult terrain) is absolutely incredible. I wish I had somewhere to write a review for this module and your work because it'd be 10/10

**Comment by caewok** [comment]
I modified the graphical overlay in v0.4.9 to use just the vertical lines for ramps/steps instead of the horizontal/vertical edging. This should improve how the ramp graphics look. I am a bit limited, though, in that the ramp graphics are done in the webGL shader. My expertise in webGL is limited and it is difficult to hack in changes that do not screw up the original version.
